version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
  web:
    container_name: backend
    build:
      context: .
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: example
    volumes:
      - .:/backend

volumes:
  db:
    driver: local
