version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: twojejedzenie3x
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ports: "5432:5432"
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: twojejedzenie3x
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
